-- 月1回の質問会アーカイブ
-- 2026-08 Photelierサロン用
--
-- 動画の本数（カリキュラム73本）は video_library.json で管理しているが、
-- 質問会は毎月増えていくので、ファイルを書き換えて再デプロイ…では回らない。
-- ここに1行足すだけで、サロンの「質問会アーカイブ」に並ぶようにする。
--
-- ドリップ（入会月による開放）はかけない。
-- 入会した月に関係なく、全員がすべての回を見られる。

create table if not exists qa_sessions (
  id          bigint generated by default as identity primary key,
  held_on     date not null,                 -- 開催日
  title       text not null,                 -- 例「8月の質問会」
  vimeo_id    text not null,                 -- Vimeoの動画ID
  vimeo_h     text,                          -- 限定公開のときのハッシュ（?h=xxxx）
  note        text,                          -- その回で話した内容のメモ（一覧に小さく出る）
  created_at  timestamptz not null default now()
);

create index if not exists qa_sessions_held_on_idx on qa_sessions (held_on desc);

-- 読み書きはサーバー（service_role）経由だけ。ブラウザから直接は触れない。
alter table qa_sessions enable row level security;
