-- サロンのお知らせ（一斉連絡）
-- 2026-08 Photelierサロン用
--
-- 質問会の日程、リアルイベントの案内など、会員さん全員に伝えたいことを置く場所。
-- LINEのオープンチャットを作らずにここで済ませる（在籍している人にだけ届く）。
--
-- さちえ先生は /teacher の「お知らせ」から書く。
-- 会員さんはサロンのホーム画面のいちばん上で読む。

create table if not exists announcements (
  id          bigint generated by default as identity primary key,
  title       text not null,                 -- 例「9月の質問会について」
  body        text not null,                 -- 本文。改行はそのまま表示される
  created_at  timestamptz not null default now()
);

create index if not exists announcements_created_at_idx on announcements (created_at desc);

-- 読み書きはサーバー（service_role）経由だけ。ブラウザから直接は触れない。
alter table announcements enable row level security;
