-- 質問会の事前質問
-- 2026-08 Photelierサロン用
--
-- 質問会は毎月 第4金曜21時（12月だけ第3金曜）。
-- その回に向けて、会員さんが事前に質問を送れるようにする。
--
-- どの回に向けた質問かは for_session に入れる。
-- 開催3日前を過ぎた分は、翌月の回に回る（サーバー側で判定）。

create table if not exists qa_questions (
  id           bigint generated by default as identity primary key,
  email        text not null,                 -- 送った方（会員のメールアドレス）
  name         text not null,                 -- 画面に出るお名前
  body         text not null,                 -- 質問の内容
  for_session  date not null,                 -- どの回に向けた質問か
  answered     boolean not null default false, -- 質問会で答えたら true
  created_at   timestamptz not null default now()
);

create index if not exists qa_questions_session_idx on qa_questions (for_session desc, created_at);

-- 読み書きはサーバー（service_role）経由だけ。ブラウザから直接は触れない。
alter table qa_questions enable row level security;
